/**
 * The platform's permission vocabulary and the system roles built from it.
 * Mirrors docs/security/permission-matrix.md — that document is the spec, this
 * file is its executable form.
 */
export const PERMISSIONS = [
  'organization:manage',
  'organization:read',
  'workspace:manage',
  'billing:manage',
  'billing:read',
  'user:manage',
  'user:read',
  'role:manage',
  'apikey:manage',
  'audit:read',
  'team:manage',
  'queue:manage',
  'taxonomy:manage',
  'customer:read',
  'customer:create',
  'customer:update',
  'customer:delete',
  'customer:merge',
  'customer:export',
  'conversation:read',
  'conversation:read_all',
  'conversation:create',
  'conversation:update',
  'conversation:assign',
  'message:create',
  'ticket:read',
  'ticket:create',
  'ticket:update',
  'ticket:delete',
  'ticket:assign',
  'sla:manage',
  'sla:read',
  'routing:manage',
  'knowledge:read',
  'knowledge:create',
  'knowledge:update',
  'knowledge:publish',
  'knowledge:delete',
  'agent:read',
  'agent:create',
  'agent:update',
  'agent:publish',
  'agent:execute',
  'workflow:manage',
  'execution:read',
  'tool:manage',
  'tool:execute',
  'memory:read',
  'memory:delete',
  'guardrail:manage',
  'copilot:execute',
  'automation:manage',
  'qc:template_manage',
  'qc:evaluate',
  'qc:read_own',
  'qc:read_all',
  'qc:dispute',
  'qc:calibrate',
  'analytics:read',
  'analytics:read_all',
  'report:manage',
  'report:export',
  'notification:manage',
  'integration:manage',
  'governance:manage',
  'eval:manage',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_KEYS = [
  'owner',
  'administrator',
  'supervisor',
  'qa_manager',
  'agent',
  'ai_builder',
  'analyst',
  'viewer',
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

const AGENT_PERMISSIONS: Permission[] = [
  'organization:read',
  'customer:read',
  'customer:create',
  'customer:update',
  'conversation:read',
  'conversation:create',
  'conversation:update',
  'conversation:assign',
  'message:create',
  'ticket:read',
  'ticket:create',
  'ticket:update',
  'ticket:assign',
  'sla:read',
  'knowledge:read',
  'agent:execute',
  'tool:execute',
  'copilot:execute',
  'qc:read_own',
  'qc:dispute',
];

const SUPERVISOR_PERMISSIONS: Permission[] = [
  ...AGENT_PERMISSIONS,
  'user:read',
  'team:manage',
  'queue:manage',
  'taxonomy:manage',
  'customer:merge',
  'conversation:read_all',
  'sla:manage',
  'routing:manage',
  'knowledge:create',
  'knowledge:update',
  'knowledge:publish',
  'agent:read',
  'execution:read',
  'memory:read',
  'automation:manage',
  'qc:evaluate',
  'qc:read_all',
  'analytics:read',
  'analytics:read_all',
  'report:manage',
  'report:export',
  'notification:manage',
];

const ADMIN_PERMISSIONS: Permission[] = [
  ...SUPERVISOR_PERMISSIONS,
  'organization:manage',
  'workspace:manage',
  'billing:read',
  'user:manage',
  'role:manage',
  'apikey:manage',
  'audit:read',
  'customer:delete',
  'customer:export',
  'ticket:delete',
  'knowledge:delete',
  'agent:create',
  'agent:update',
  'agent:publish',
  'workflow:manage',
  'tool:manage',
  'memory:delete',
  'guardrail:manage',
  'qc:template_manage',
  'qc:calibrate',
  'integration:manage',
  'governance:manage',
  'eval:manage',
];

export const SYSTEM_ROLES: Record<
  RoleKey,
  { name: string; description: string; permissions: Permission[] }
> = {
  owner: {
    name: 'Organization Owner',
    description: 'Full control including billing and governance',
    permissions: [...new Set<Permission>([...ADMIN_PERMISSIONS, 'billing:manage'])],
  },
  administrator: {
    name: 'Administrator',
    description: 'Configures the organization and manages access',
    permissions: [...new Set(ADMIN_PERMISSIONS)],
  },
  supervisor: {
    name: 'Supervisor',
    description: 'Runs queues and teams, monitors quality and SLAs',
    permissions: [...new Set(SUPERVISOR_PERMISSIONS)],
  },
  qa_manager: {
    name: 'QA Manager',
    description: 'Owns quality scorecards, evaluation and calibration',
    permissions: [
      'organization:read',
      'user:read',
      'audit:read',
      'customer:read',
      'conversation:read',
      'conversation:read_all',
      'ticket:read',
      'sla:read',
      'knowledge:read',
      'agent:read',
      'memory:read',
      'qc:template_manage',
      'qc:evaluate',
      'qc:read_own',
      'qc:read_all',
      'qc:dispute',
      'qc:calibrate',
      'analytics:read',
      'analytics:read_all',
      'report:manage',
      'report:export',
      'eval:manage',
    ],
  },
  agent: {
    name: 'Agent',
    description: 'Handles conversations and tickets',
    permissions: [...new Set(AGENT_PERMISSIONS)],
  },
  ai_builder: {
    name: 'AI Builder',
    description: 'Builds, evaluates and publishes AI agents and workflows',
    permissions: [
      'organization:read',
      'apikey:manage',
      'customer:read',
      'knowledge:read',
      'knowledge:create',
      'knowledge:update',
      'knowledge:publish',
      'agent:read',
      'agent:create',
      'agent:update',
      'agent:publish',
      'agent:execute',
      'workflow:manage',
      'execution:read',
      'tool:manage',
      'tool:execute',
      'memory:read',
      'memory:delete',
      'guardrail:manage',
      'automation:manage',
      'analytics:read',
      'integration:manage',
      'eval:manage',
    ],
  },
  analyst: {
    name: 'Analyst',
    description: 'Reads operational data and builds reports',
    permissions: [
      'organization:read',
      'billing:read',
      'user:read',
      'audit:read',
      'customer:read',
      'customer:export',
      'conversation:read',
      'conversation:read_all',
      'ticket:read',
      'sla:read',
      'knowledge:read',
      'agent:read',
      'execution:read',
      'qc:read_all',
      'analytics:read',
      'analytics:read_all',
      'report:manage',
      'report:export',
    ],
  },
  viewer: {
    name: 'Viewer',
    description: 'Read-only access to day-to-day operations',
    permissions: [
      'organization:read',
      'user:read',
      'customer:read',
      'conversation:read',
      'ticket:read',
      'sla:read',
      'knowledge:read',
      'agent:read',
      'analytics:read',
    ],
  },
};

/**
 * True when the granted set satisfies `required`. `*` is the system wildcard and
 * `resource:manage` implies every action on that resource.
 */
export function hasPermission(granted: readonly string[], required: string): boolean {
  if (granted.includes('*') || granted.includes(required)) return true;
  const [resource] = required.split(':');
  return granted.includes(`${resource}:manage`);
}

export function hasAnyPermission(granted: readonly string[], required: readonly string[]): boolean {
  return required.some((permission) => hasPermission(granted, permission));
}

export function hasAllPermissions(
  granted: readonly string[],
  required: readonly string[],
): boolean {
  return required.every((permission) => hasPermission(granted, permission));
}
